# Generated by Django 6.0.5 on 2026-05-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recruiter',
            new_name='user',
        ),
    ]
